alphagov/bouncer

lib/bouncer/preemptive_rules.rb
spec/features/http_request_handling_spec.rb

These rules handle multisurfaced AAIB MAIB and RAIB content.
They are not designed to handle the scenario like www.aaib.gov.uk/sites/raib/whatever, that can be handled under separate cover, should we decide that a 404 is not appropriate. 
For clarity, these three sites surface pages in two separate urlspaces. Content at ```/sites/aaib/foo/bar``` equals content at ```/foo/bar```

Add rules to handle multisurfaced AAIB, MAIB and RAIB content.

---

lib/bouncer/fallback_rules.rb
spec/features/http_request_handling_spec.rb

This is dependent on https://github.com/alphagov/transition-config/pull/1070 and should not be merged or deployed until that config takes effect.

Remove GDS blog rules

---

lib/bouncer/outcome/base.rb
spec/features/http_request_handling_spec.rb

- The corresponding Transition Tool change is
https://github.com/alphagov/transition/pull/485 - see there for
context.

Add *.nhs.uk as an automatically allowed ending for a hostname

---

lib/bouncer/preemptive_rules.rb
spec/features/http_request_handling_spec.rb

The homepage of www.planningportal.gov.uk redirects to a
session-based URL ([example](http://www.planningportal.gov.uk/wps/portal/portalhome/unauthenticatedhome/!ut/p/c5/04_SB8K8xLLM9MSSzPy8xBz9CP0os3gjtxBnJydDRwMLbzdLA09nSw_zsKBAIwN3U_1wkA6zeHMXS4gKd29TRwNPI0s3b2e_AGMDAwOIvAEO4Gig7-eRn5uqX5CdneboqKgIAGUwqho!/dl3/d3/L2dBISEvZ0FBIS9nQSEh/.)) We found ~18,000 of these URLs while
building a list of URLs for the site, and users may well have
bookmarked them, so we should redirect them.
This adds pre-emptive redirect that points to the homepage, which
will then redirect to whatever we map `/` to, which will avoid
having to duplicate that redirect destination..

Add rule for planning-portal session-variant homepage

---

boot.rb

In order to twelve-factorise Bouncer, we should use `DATABASE_URL` so that the
database to establish a connection to can be sent by environment variables.
Set a fall-back mechanism to read from the YAML file copied during
deployment if no `DATABASE_URL` environment variable exists.
There's a related Puppet pull request to create the environment variable by interpolating
Hiera values: https://github.gds/gds/puppet/pull/3388

Twelve-factorise PostgreSQL connection

---

lib/bouncer.rb
lib/bouncer/app.rb
lib/bouncer/cacher.rb
lib/bouncer/outcome/canary.rb
spec/features/http_request_handling_spec.rb
spec/units/bouncer/app_spec.rb

If Bouncer goes down outside normal working hours, the people on call should be notified. The app and the check should also be documented in the opsmanual so that they are able to take appropriate action if necessary.
This PR adds a canary route at `/__canary__` which checks to see if it can select from 3 of the tables. If any of these 3 checks throw an error or can't connect, we return a `503`. [Ticket](https://trello.com/c/FrsSm5oK/69-alert-out-of-hours-if-bouncer-is-down).
Original work done by @jennyd. Props to her for starting and helping me with this. ✊✊✊✊✊

Canary route

---

Gemfile
Gemfile.lock

ActiveRecord: 4.1.11 -> 4.1.14.1 which covers CVE-2015-7577 and
CVE-2016-0753
Nokogiri: 1.6.0 -> 1.6.7.2 which covers CVE-2015-7499, CVE-2015-5312,
CVE-2015-7497, CVE-2015-7498, CVE-2015-7499, CVE-2015-7500, CVE-2015-8241,
CVE-2015-8242, CVE-2015-8317, CVE-2015-1819, CVE-2015-7941_1,
CVE-2015-7941_2, CVE-2015-7942, CVE-2015-7942-2, CVE-2015-8035,
CVE-2015-7995, CVE-2013-2877, and CVE-2014-0191 (mostly libxml).

Upgrade activerecord and nokogiri

---

public/gone.css

Switch to the new green, which is more neon and is web safe by default.
https://trello.com/c/p3BYq1Rd/295-defra-colour-change-to-brand

[DO NOT MERGE UNTIL Feb 18] Update defra green

---

lib/bouncer/fallback_rules.rb
spec/features/http_request_handling_spec.rb

These paths contain address and postcode search parameters, so can't be
mapped.
These rules don't preserve the search - they just redirect to the new price
paid dataset search page. Land Registry have confirmed that this is the right
URL to redirect to.
This rule could be a one-liner, but I thought it was clearer as a `case`:
```ruby
redirect('http://landregistry.data.gov.uk/app/ppd') if request.path =~ %r{(^/sold-prices)|(^/price-paid-record)}
```
This should fix the vast majority of [the 404s Bouncer is serving right now](https://kibana.publishing.service.gov.uk/kibana#/dashboard/elasticsearch/Bouncer).

Add fallback rules for Land Registry house prices site

---

config/airbrake.rb

For the time being this file will still be overwritten at deploy time, but once we remove that functionality from govuk-app-deployment this new file will start to be used.

Read Airbrake config from environment

---

Gemfile
Gemfile.lock

We've fixed a bug in Optic14n to resolve this error in Transition:
To fix https://errbit.publishing.service.gov.uk/apps/530f56010da115868600173d/problems/577c047a65786352db2b0400
This error occurs when canonicalizing query strings.  It appears that not every
character emerges unscathed from this process.  In this case, having `%E2`
(which is equivalent to "â")  in a key of a query string results in the error
found in Errbit.
We need to keep Bouncer and Transition in step so they can use the same
canonicalization code.
See https://trello.com/c/ihTQRRMX/325-encoding-error-on-hits-import-in-transition
for further explanation and context.

Bump Optic14n to stay in step with Transition

---

Gemfile
Gemfile.lock

This is necessary due to an unsafe query generation risk in Active Record
Advisory: CVE-2016-6317
URL: https://groups.google.com/forum/#!topic/rubyonrails-security/rgO20zYW33s
A PR to keep Transition in sync will also be raised ( https://github.com/alphagov/transition/pull/521 )

Upgrade Active Record to 4.2.7.1

---

lib/bouncer/fallback_rules.rb

We're [adding these domains as aliases of the site](https://github.com/alphagov/transition-config/pull/1201), so need to add them here as
well for the rule to apply to them. number10.gov.uk was already here despite
not being in transition-config.

Add aliases to fallback rule for number10 news

---

db/structure.sql

Bouncer and Transition share a database, so we should keep the `structure.sql` here up to date when we modify the database schema in Transition. It looks like we haven't done this for a while, so there are a few changes, although none which affect tables used by Bouncer.
Generated with `rake db:structure:dump` in Transition and copied over.
https://trello.com/c/MGtcYgQV/549-fix-limit-on-archive-url-length-when-importing-batches-in-transition

Update db/structure.sql from Transition

---

Gemfile
Gemfile.lock
Rakefile
config.ru
config/airbrake.rb
lib/bouncer.rb

This commit makes the app use Sentry for error reporting.
- Remove Airbrake gem & config
- Add [govuk_app_config][] which adds the Sentry gem ([sentry-raven][])
[govuk_app_config]: https://github.com/alphagov/govuk_app_config
[sentry-raven]: https://github.com/getsentry/raven-ruby
https://trello.com/c/smPvoz8w

Use Sentry for error reporting

---

lib/bouncer.rb
lib/bouncer/error_reporting.rb

We've already seen 130K `PG::ConnectionBad` errors reported to Sentry:
https://sentry.io/govuk/app-bouncer/issues/335728174
This should filter out the errors per https://docs.sentry.io/clients/ruby/config/
I've tried to solve this by upping the connection limit on the transition postgres machines in https://github.com/alphagov/govuk-puppet/pull/6448, but that didn't seem to have helped. I suspect that it's an application issue, perhaps related to the upgrade in https://github.com/alphagov/bouncer/commit/91b6c7b3cc25af9eb18826d144a406af4bec9830.
I've created a ticket for a longer term solution: 
https://trello.com/c/NSVAgy9D/170-fix-database-errors-in-bouncer

Stop reporting PG::ConnectionBad

---

public/gone.css

DCMS and Scotland Office were recently [reslugged][transition]. This change updates the CSS classes to match the new slugs.
[transition]: https://github.com/alphagov/transition-config/pull/1254#discussion_r144515942

Reslug DCMS and Scotland Office

---

Gemfile
Gemfile.lock

This is now included as a dependency in govuk_app_config.
To be merged after https://github.com/alphagov/bouncer/pull/156

Remove unicorn gem

---

Rakefile
boot.rb
config/database.yml

Unfortunately it appears to be quite hard to invoke ActiveRecord
DB tasks outside of the Rails framework [1].
[1]: https://jer-k.github.io/add-active-record-rake-tasks-to-gem/

Add support for remote Docker database

---

lib/bouncer/app.rb
lib/bouncer/outcome/healthcheck.rb
spec/features/http_request_handling_spec.rb

This ensures that the app is able to connect to ActiveRecord.
This is a precursor to enabling CD on Bouncer.
Trello: https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps

Improve healthcheck using govuk_app_config

---

lib/bouncer.rb
lib/bouncer/app.rb
lib/bouncer/canonicalized_request.rb
lib/bouncer/outcome/bad_request.rb
lib/bouncer/request_context.rb
spec/units/bouncer/app_spec.rb
spec/units/bouncer/canonicalized_request_spec.rb

We're seeing fairly high volumes of errors in Sentry:
https://sentry.io/organizations/govuk/issues/2086648123/events/80d68b1848f24f7b82e08cb839b64dc2/?project=202210
These errors happen when an invalid (malformed) host is passed to
Bouncer, leading to a `Addressable::URI::InvalidURIError` being
raised. We see an error message of the form:
`Invalid character in host: 'foo.gov.uk))'("),,)'`
We can't stop those requests from being made, but we can avoid
logging inactionable errors in Sentry. This change detects the
`Addressable::URI::InvalidURIError` exception and returns a 400
Bad Request error gracefully: https://httpstatuses.com/400
It wasn't straightforward to add a test for this, as any attempt
to `get url` (where `url` is malformed as above) would break at
the RSpec level and not reach …

Handle invalid hosts gracefully

---

lib/bouncer/app.rb

In #283, we added code to capture `Addressable::URI::InvalidURIError`
exceptions and return 400 Bad Request responses. This was in order
to prevent logging this unactionable error in Sentry:
https://sentry.io/organizations/govuk/issues/2086648123/?project=202210&referrer=slack
The fix didn't work, because we capture the exception too late in
the logic, after `context.request.path` and `context.host.nil?`
have been called in `Bouncer::App.call`. By this point, the
exception has been raised already, before we have had a chance to
call `context.valid?`, so the Sentry errors have still been
happening.
We now check `context.valid?` as the very first thing before
digging into its internals.
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Return `Outcome::BadRequest` early if bad request

---

README.md
startup.sh

Rewrite README to favour GOV.UK Docker
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
Depends on: https://github.com/alphagov/govuk-docker/pull/479
This was tricky because this repo shares a database with Transition,
and the features the app provides are quite advanced.
I don't know much about this repo myself. Since the aim of this PR is
to fix old references to the Dev VM, I'm going to defer:
- Extending the introduction with a comprehensive description of the
features of this repo and how it interacts with others.
- Adding a nomenclature section to explain terms like "site" and "alias".

Rewrite readme

---

config/unicorn.rb

Since [govuk_app_config#196](https://github.com/alphagov/govuk_app_config/pull/196)
and [govuk_app_config#197](https://github.com/alphagov/govuk_app_config/pull/197),
we're seeing errors in Sentry during the data sync, where we have
configured these to be ignored. Example:
https://sentry.io/organizations/govuk/issues/2410319407/?project=202210&referrer=slack
The exception chain in the above Sentry error contains
`ActiveRecord::StatementInvalid` and `PG::UndefinedTable`. We have
`PG::Error` defined as a datasync-ignorable exception by default.
[`PG::UndefinedTable` has `PG::Error` as an ancestor](https://github.com/ged/ruby-pg/blob/00cb2ecfaa70470234ee83efbd942b5e6ea0f4ea/spec/pg_spec.rb#L35-L39),
so it should be ignoring the exception.
To determine whether the exception chain …

Explitly ignore UndefinedTable and StatementInvalid exceptions

---

config/unicorn.rb

Reverts alphagov/bouncer#303 as it did not fix the issue we were seeing in Sentry.

Revert "Explitly ignore UndefinedTable and StatementInvalid exceptions"

---

Jenkinsfile
Rakefile

This changes the JenkinsFile to use postgres 13. Bouncer shares its 
database with transition so the database name is transition-test.
Postgres 13 is available at port `54313` on the CI server. By explicitly 
setting the `TEST_DATABASE_URL`, we're telling Rails to use that 
Postgres server.
Previously, Rails implicitly used the default Postgres port `5432` which 
is a Postgres 9.6 server.
We now need to specify the port number and require no password when reseting the database in the CI environment.
Trello ticket: https://trello.com/c/zVdVJqFM

Use postgres 13 when running tests in CI

---

Rakefile

db:reset calls dropdb to do the drop/rebuild. If there's
no port specified in the database url you still get a
-p but with no parameter, causing the command to fail.

Fix build bug where no port is specified for database

---

boot.rb

This avoids the need to restart the app when making certain kinds of changes when running the app in development mode.

Set bootsnap development_mode when in dev mode.

---

boot.rb
config/prometheus.rb

This aims to add Prometheus support to Bouncer for use with EKS. Other GOV.UK Ruby apps normally put this config in `config/initialize` because they use Rails. But Bouncer doesn't use Rails, so instead we're putting it in `/config` and ~~seeing if it loads-in~~ explicitly requiring it from `boot.rb`. ~~I'm going by the assumption that this should work because Unicorn is configured in a similar approach.~~
I don't expect this change by itself to do anything, unless the environment variable `GOVUK_PROMETHEUS_EXPORTER` is set to `true`. This envvar is currently set globally in our k8s app ConfigMap.

Add Support for Prometheus Exporting

---

README.md

Add some exampled of domains which are redirected using bouncer.
Trello card: https://trello.com/c/EJXbs0ae/3120-retire-govuk-ithc-documentation-repository-2

Add examples of domain names which are served by bouncer

---

config.ru

Reverts alphagov/bouncer#407
I must have done something wrong here. Looks like I've introduced a memory leak. Rolling back until it gets figured out

Revert "Include prometheus middleware in the app"

---

config.ru

We need to do this [differently to Rails, Sinatra](https://github.com/alphagov/govuk_app_config/blob/main/lib/govuk_app_config/govuk_prometheus_exporter.rb) because we're using a plain Rack middleware stack.
We need to use the `prepend` option for instrumentation as the app crashes if we use the default `alias_method`. Some documentation on this is in the [prometheus_exporter README](https://github.com/discourse/prometheus_exporter#choosing-the-style-of-method-patching)
My previous effort worked in terms of extracting the metrics, but seemed to leak memory horribly. I think I'd just got it very wrong. The workload stats on integration for this change seem stable after a couple of hours, so I think this is good to go.
(App metrics are working)
⚠️ This repo is Continuously Deployed: make …

Add prometheus metrics to bouncer

---

README.md

We've recently retired the transition-config project. Sites are now
added to Transition using a user interface, even in local development.
The README's manual testing instructions now reflect that new process.

Remove references to transition-config from docs

---

lib/bouncer/request_context.rb
spec/features/http_request_handling_spec.rb

At present, when we redirect a URL to the National Archives, we use the http scheme.
The first thing the NA CDN does is _permanently_ redirect this to the same URL over TLS (some lines removed for brevity):
```
> curl -L -Is http://guidanceanddata.defra.gov.uk/
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 03 Nov 2023 10:43:34 GMT
Content-Type: text/html
Location: http://webarchive.nationalarchives.gov.uk/20150423095755/http://guidanceanddata.defra.gov.uk/
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Fri, 03 Nov 2023 10:43:34 GMT
Content-Type: text/html
Location: https://webarchive.nationalarchives.gov.uk/20150423095755/http://guidanceanddata.defra.gov.uk/
X-Cache: Redirect from cloudfront
```
We can remove a redirect hop from each of these by updating the default NA …

Send National Archives redirects straight to https

---

lib/bouncer/outcome/global_type.rb
lib/site.rb

In https://github.com/alphagov/transition/pull/1473, we have removed the need for an abbreviation to be specified for a site.
Therefore updating this app to no longer use that field since it may not always be present.
[Trello card](https://trello.com/c/HaVI5NDq)

Change use of abbreviation to primary hostname

---

public/google-analytics.js
templates/404.erb
templates/410.erb

UA is going to be decommissioned imminently, so these aren't going to work shortly.
If we need page view information for bouncer, we can get it from the CDN logs.
Removing analytics rather than replacing it with GA4 means we don't have to solve a cookie consent problem.

Remove google analytics code from 404 / 410 pages

---

README.md

We noticed comments about this in Bouncer and Transition, but no obvious explanation in the comments or their related Git history. We had to ask a longer-serving member of the team for clarity on this (and whether it still applied), so we're documenting this to aid future readers
---

Explain Bouncer/Transition dependency sync

---

Gemfile
Gemfile.lock

dependabot has opened a pull request on Transition to upgrade Rails to 7.2.1.1 but hasn't opened a pull request to upgrade activerecord on Bouncer. We aim to keep these in sync since they share a database, so I'm manually upgrading here
---

Upgrade activerecord to 7.2.1.1

---

Gemfile
Gemfile.lock

We have a Dependabot alert (here and for Rails on a few other apps) about Active Record 7.2.2. This upgrades Active Record to a patched version. We aren't ready to upgrade to v8 yet
https://github.com/alphagov/bouncer/security/dependabot/65
---

Upgrade Active Record to 7.2.2.1
